export const PATHS = {
  home: "/",
  adminLogin: "/login/admin",
  employeeLogin: "/login/empleado",

  admin: "/admin",
  adminSale: "/admin/ventas",
  adminSalesProduct: "/admin/ventas/producto",
  adminSalesService: "/admin/ventas/servicio",
  adminSalesList: "/admin/ventas/lista",
  adminSalesEdit: "/admin/ventas/editar",
  adminEmployees: "/admin/empleados",
  adminClients: "/admin/clientes",
  adminProducts: "/admin/productos",
  adminServices: "/admin/servicios",
  adminProductCategories: "/admin/categorias-productos",
  adminServiceCategories: "/admin/categorias-servicios",
  adminReports: "/admin/reportes",
  adminProfile: "/admin/perfil",

  employee: "/empleado",
  employeeSale: "/empleado/ventas",
  employeeSalesProduct: "/empleado/ventas/producto",
  employeeSalesService: "/empleado/ventas/servicio",
  employeeMySales: "/empleado/mis-ventas",
  employeeCashClosing: "/empleado/corte-caja",
  employeeProfile: "/empleado/perfil",
};
